# -*- coding: utf-8 -*-
"""Stable Diffusion 2.1 Text2Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BeftkTJ066Ao6RpYx0wKzMrvs-rkeQ8E
"""

!pip install diffusers transformers accelerate scipy safetensors

import torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler

model_id = "stabilityai/stable-diffusion-2-1"

# Use the DPMSolverMultistepScheduler (DPM-Solver++) scheduler here instead
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to("cuda")
pipe.enable_attention_slicing()

# Commented out IPython magic to ensure Python compatibility.
# %%time
# prompt = "a photo of cristiano ronaldo siuu"
# image = pipe(prompt).images[0]
# 
# image.save("walpaper.png")

image

