# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jMw3bYdSPK8UI6JNkARoZquVh2VV5Xdq
"""

y = 120
x = "hai"

x = 5
print(type(x))

y = 0.5
print(type(y))

mobil = "hijau"
print(type(mobil))


print(5*2)
print(5*2.2)

x = 5
(x**2) + (x**3) + (x+2) - (x/2)

uang = 25000
if uang >= 25000:
  print("uang cukup")

else:
  print("uang tidak cukup")

price = 25000
uang = 10000
if price == uang:
    print("uang pas")
elif price < 25000:
  print("uang lebih")
else:
  print("uang tidak cukup")

price = 25000
kondisi ='baik'
if price >= 25000:
    print("uang pas")
    if kondisi ==
elif price < 25000:
  print("uang lebih")
else:
  print("uang tidak cukup")

for i in range(10):
  print("saya berjanji tidak akan mengulangi lagi")

for i in range(10):
  print (i)

j = 0
while j<10:
  print (j)
  j = j + 1

total = 0
for i in range(2,6):
  total = total + i

  print(total)

total = 0
for i in range(1,1000):
  total = total + i

  print(total)

for i in range(1,11,2):
  print(i, end="")

for i in range(1,6):
  for j in range(1,3):
    print("ini lorong ke-", i, "kamar ke-", j)

lanjut = True
while(lanjut):
  option = input("lanjut atau tidak? (y/n)")
  if(option == 'n'):
    lanjut = False
    print("program berhenti!")

def perkalian(angka1, angka2):
  return angka1*angka2

  hasil = perkalian(10,2)
  print(hasil)

